### ISSUE TITLE
incorrect value: buf[0] is not 0x0f and buf[24] is not 0x00

### ISSUE THREAD

**Issue by giangthewalkingman** [osos11-Git/STM32_RadioLink_SBUS_DMA#1]
### Incorrect value for buffer
Instead of using a transistor, I connect directly the receiver x8r to the stm32f407 discovery board with supply from the board itself. In debug window, I observe the value of buf[0] and buf[24], it shows unstable/fluctuating value 100/250/... or something else (in decimall) and does not match with the correct value as 0x0f and 0x00. I do not modify the original function.
I even deleted the if condition so that I can observe the value of CH[x] without the condition of "buf[0]==0x0f", it doesn't match with the value from my FrSky transmitter.
Via reading information of x8r, it is also an inverted serial logic receiver.
**My setup:** 
1. connect receiver directly to the board (5V pin to supply, gnd to gnd, signal to PA3) without the transistor
2. f407discovery board.
3. clock is 25MHz.
4. usart is set similarly to usart in github repository.
5. I do not modify the logic of the code.

**Comment by osos11-Git** [comment]
I have no idea how FrSky implements SBUS. 
My code works great with Radiolink RC6GS/R7FG.
